stages:
  - pages
  - deploy

update_docs:
  stage: pages
  image: node:8.9.3
  script:
    - yarn
    - yarn run analyze
    - yarn run build-docs
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
  tags:
    - docker

update_catalyst_elements:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y curl
  script:
    - VERSION_REGEX='^v?([0-9]+\.)?([0-9]+\.)?([0-9]+)$'
    - if [[ $CI_COMMIT_TAG =~ $VERSION_REGEX ]]; then
    -   curl -X POST -F token=$CATALYST_ELEMENTS_PIPELINE_TOKEN -F ref=CATALYST_ELEMENTS_PIPELINE_REF https://gitlab.wgtn.cat-it.co.nz/api/v4/projects/1077/trigger/pipeline
    - else
    -   echo "Skipping - $CI_COMMIT_TAG is not a version tag."
    - fi
  only:
    - tags
